# ============================================================
# BonnieVerify Configuration
# ============================================================
# These codes serve as secret keys for command verification,
# reset, exclusive access, and configuration reload functionality.
bonnie_codes:
  verify_verify: "AAA"        # Secret code for verification (OP granting)
  verify_reset: "BBB"         # Secret code for removing all OP status
  verify_exclusive: "CCC"     # Secret code for exclusive commands (OP & LuckPerms)
  verify_reload: "DDD"        # Secret code to reload plugin configurations


# ============================================================
# Core Plugin Configuration
# ============================================================
config:

  # ----------------------------------------------------------
  # Permissions Configuration
  # ----------------------------------------------------------
  # Defines trusted administrators who bypass restrictions,
  # frequency of permission checks, and enforcement of survival mode.
  permissions:
    allowed_admins:
      - XXX                   # List of admin usernames exempt from restrictions
    check_interval: 1          # Interval in seconds for permission validation
    force_survival_mode: true  # Forces players to stay in survival mode
    prevent_op_commands: true  # Blocks execution of OP-related commands by unauthorized players

  # ----------------------------------------------------------
  # Security Actions & Punishments
  # ----------------------------------------------------------
  # Automatic enforcement actions triggered upon security violations.
  actions:
    punishments:
      clear_permissions: true  # Removes all permissions from the offender
      clear_op: true           # Revokes OP status
      kick_player: true        # Kicks the player from the server
      ban_player: true         # Bans the player from the server

  # ----------------------------------------------------------
  # Login Security Settings
  # ----------------------------------------------------------
  # Manages login attempt limits, temporary blocks, and allowed username patterns.
  login:
    max_attempts: 5                    # Maximum allowed failed login attempts
    block_time: 3600                  # Block duration in seconds (1 hour)
    allowed_username_regex: ^[a-zA-Z0-9_]{3,16}$  # Regex pattern for valid usernames

  # ----------------------------------------------------------
  # Command Block Settings
  # ----------------------------------------------------------
  # Prevents command block exploits or misuse.
  blocks:
    prevent_command_blocks: true      # Disables command block usage if true

  # ----------------------------------------------------------
  # Plugin Restrictions
  # ----------------------------------------------------------
  plugins:
    blocked:
      - zPleumCORE                   # Plugins blacklisted from operation/interference
    hide_plugin_commands: true        # Conceals commands related to blocked plugins

  # ----------------------------------------------------------
  # Logging Settings
  # ----------------------------------------------------------
  logging:
    enabled: true                    # Enables logging of plugin activities
    detailed: true                   # Enables verbose logging with detailed information


# ============================================================
# Security Enforcement & Command Restrictions
# ============================================================
security:

  commands:
    blocked:                        # Commands globally blocked to protect server integrity
      - op
      - deop
      - kick
      - plugman
      - minecraft:op
      - bukkit:op
      - spigot:op
      - rl
      - reload
      - stop
      - plugins
      - pl
      - '?'
      - timings
      - tps
      - cmi:spawn
      - cmi:warp
      - cmi:heal
      - cmi:tp
      - cmi:tpaccept
      - cmi:tphere
      - cmi:weather
      - cmi:time
      - cmi:give
      - cmi:fly
      - cmi:clearinventory
      - cmi:feed
      - cmi:back
      - cmi:flyspeed
      - cmi:speed
      - cmi:jump
      - cmi:god
      - cmi:mute
      - cmi:ban
      - cmi:pardon
      - cmi:kick
      - cmi:banip
      - cmi:unbanip
      - cmi:banlist
      - cmi:playerinfo
      - cmi:admin
      - cmi:adminmode
      - cmi:reload
      - cmi:msg
      - cmi:sendmessage
      - cmi:clear
      - lp
      - perms
      - luckperms
      - luckperms:info
      - luckperms:user
      - luckperms:group
      - luckperms:track
      - luckperms:permission
      - luckperms:inheritance
      - luckperms:permissionset
      - luckperms:group:add
      - luckperms:user:add
      - luckperms:track:add
      - luckperms:group:remove
      - luckperms:user:remove
      - luckperms:track:remove
      - luckperms:permission:remove
      - luckperms:group:set
      - luckperms:user:set
      - luckperms:track:set
      - luckperms:permission:set
      - luckperms:check
      - luckperms:promote
      - luckperms:demote
      - luckperms:clear
      - luckperms:group:rename
      - luckperms:user:rename
      - luckperms:track:rename
      - luckperms:permission:add
      - luckperms:permission:remove
      - luckperms:group:delete
      - luckperms:user:delete
      - luckperms:track:delete
      - luckperms:permissible:clear
      - luckperms:exempt
      - luckperms:exempt:add
      - luckperms:exempt:remove
      - luckperms:message
      - luckperms:debug
      - luckperms:update
      - luckperms:save
      - luckperms:reload
      - about
      - ver
      - help
      - bukkit
      - bukkit:plugins
      - pl
      - plugin
      - plugins

    rcon-blocked:                  # Commands blocked when issued via RCON for security reasons
      - op
      - deop
      - kick
      - ban
      - pardon
      - whitelist
      - reload
      - stop
      - restart
      - luckperms
      - plugman

  permissions:
    allowed_admins:                # List of admins allowed to bypass some security restrictions
      - XXX
    check_interval: 1              # Interval in seconds to check permissions validity
    force_survival_mode: true      # Enforce survival mode for all players
    prevent_op_commands: true      # Block unauthorized OP command execution

  actions:
    punishments:                  # Defines automatic punitive actions for security violations
      clear_permissions: true     # Remove all permissions from offender
      clear_op: true              # Remove OP status from offender
      kick_player: true           # Kick offender from server
      ban_player: true            # Ban offender from server

  login:
    max_attempts: 5               # Maximum number of failed login attempts allowed
    block_time: 3600             # Duration (in seconds) for which a player is blocked after max attempts
    allowed_username_regex: ^[a-zA-Z0-9_]{3,16}$  # Regex defining allowed username formats

  blocks:
    prevent_command_blocks: true  # Disallow usage of command blocks to avoid abuse

  plugins:
    blocked:                     # Plugins to block or restrict
      - zPleumCORE
    hide_plugin_commands: true    # Hide commands of blocked plugins from players

  logging:
    enabled: true                # Enable logging of plugin events
    detailed: true               # Enable detailed logs for in-depth monitoring


# ============================================================
# Movement & Config Integrity Settings
# ============================================================
movement:
  max_speed: 10                  # Maximum allowed player speed to prevent speed hacking

config_integrity:
  enabled: true                 # Enable automatic integrity checks on configuration files
